{"name": "Get orders for unauthorized user", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 401\n +  where 403 = <Response [403]>.status_code", "trace": "self = <Diplom_2.tests.test_get_user_orders.TestGetUserOrders object at 0x00000128F9426350>\n\n    @allure.title('Get orders for unauthorized user')\n    def test_get_orders_unauthorized(self):\n        response = self.api.get_user_orders('invalid_token')\n>       assert response.status_code == 401\nE       assert 403 == 401\nE        +  where 403 = <Response [403]>.status_code\n\ntests\\test_get_user_orders.py:29: AssertionError"}, "start": 1751986481816, "stop": 1751986482018, "uuid": "eaf2b137-c820-41c6-b232-c0b48cbdea0e", "historyId": "92bf968573314a866ca27467231d26bc", "testCaseId": "92bf968573314a866ca27467231d26bc", "fullName": "tests.test_get_user_orders.TestGetUserOrders#test_get_orders_unauthorized", "labels": [{"name": "feature", "value": "Get User Orders"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "DESKTOP-42BDC19"}, {"name": "thread", "value": "24480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}